version: '3.8'

services:
  mitmweb:
    image: mitmproxy/mitmproxy
    volumes:
      - type: bind
        source: ./dump.har
        target: /dump.har
      - ./config:/home/mitmproxy/.mitmproxy
    command: mitmweb
    ports:
      - 8080:8080
      - 127.0.0.1:8081:8081