# intercept: ~u .*\/service\/graphql
# save_stream_filter: ~u .*\/service\/graphql
# hardump: /dump.har

connection_strategy: lazy
block_list:
  - /!~d edu.21-school.ru & !~d mitm.it/444

scripts:
  - ~/.mitmproxy/har.py

web_port: 8081
web_host: 0.0.0.0

block_global: false

rawtcp: false
server_replay_refresh: false
websocket: false
command_history: false